#!/usr/bin/env bash

srun -o output/bbduk/bbduk.log \
    --mail-type=ALL \
    -n1 -c8 \
    -J "bbduk2" \
    src/sh/bbduk_quick && \
srun -o output/bbnorm/bbnorm.log \
    --mail-type=ALL \
    -n1 -c8 \
    -J "bbnorm" \
    src/sh/bbnorm_quick

exit 0

