#!/usr/bin/env bash

bin/bbtools/bbnorm.sh threads=8 -Xmx55g \
    in=output/bbduk/ASW_filtered_trimmed.fastq.gz \
    out=output/bbnorm/ASW_normalised.fastq.gz \
    target=60 min=15 prefilter ecc \
    khist=output/bbnorm/hist_before.txt \
    khistout=output/bbnorm/hist_after.txt \
    peaks=output/bbnorm/peaks.txt

exit 0
